=== peratonlabs/Iliad-GIFT-lindet/config/r10_metaparameters_schema.json
{
    "$id": "https://www.peratonlabs.com/r9gift.schema.json",
    "title": "PL-GIFT Algorithm Meta-Parameters",
    "technique": "Cosine-linear weight analysis",
    "technique_description": "Computes delta cosine features and classifies with a linear model",
    "technique_changes": "xxxxx",
    "technique_type": [
        "Weight Analysis"
    ],
    "commit_id": "xxxxx",
    "repo_name": "https://github.com/plgift/coslin",
    "$schema": "https://json-schema.org/draft-07/schema",
    "description": "TrojAI schema for the GIFT team, cos-lin method",
    "type": "object",
    "required": [
        "train_$SSD_71$nfeats",
        "train_$SSD_71$ntensors",
        "train_$SSD_71$cls_type",
        "train_$SSD_71$param_batch_sz",
        "train_$SSD_71$C",
        "train_$SSD_71$feature_selection_criterion",
        "train_$SSD_71$features",
        "train_$SSD_71$normalize_for_feature_selection",
        "train_$SSD_71$sort_tensors",
        "train_$FasterRCNN_83$nfeats",
        "train_$FasterRCNN_83$ntensors",
        "train_$FasterRCNN_83$cls_type",
        "train_$FasterRCNN_83$param_batch_sz",
        "train_$FasterRCNN_83$C",
        "train_$FasterRCNN_83$feature_selection_criterion",
        "train_$FasterRCNN_83$features",
        "train_$FasterRCNN_83$normalize_for_feature_selection",
        "train_$FasterRCNN_83$sort_tensors"
    ],
    "additionalProperties": false,
    "properties": {
        "train_$SSD_71$nfeats": {
            "type": "integer",
            "minimum": 1,
            "description": "how many features to select",
            "suggested_minimum": 50,
            "suggested_maximum": 5000
        },
        "train_$SSD_71$ntensors": {
            "type": "integer",
            "minimum": 0,
            "description": "how many tensors select features from",
            "suggested_minimum": 5,
            "suggested_maximum": 100
        },
        "train_$SSD_71$cls_type": {
            "enum": [
                "LogisticRegression"
            ],
            "description": "name of classifier class (only LogisticRegression is currently supported)"
        },
        "train_$SSD_71$param_batch_sz": {
            "type": "integer",
            "minimum": 1,
            "description": "how many torch 'parameters' to look at at a time (trade off memory and disk reading)",
            "suggested_minimum": 80,
            "suggested_maximum": 80
        },
        "train_$SSD_71$C": {
            "type": "number",
            "minimum": 1e-09,
            "description": "sklearn-style regularization term.  Higher C -> less regularization. Must be positive",
            "suggested_minimum": 0.01,
            "suggested_maximum": 200.0
        },
        "train_$SSD_71$feature_selection_criterion": {
            "enum": [
                "corr",
                "auc"
            ],
            "description": "criterion for greedy feature selection"
        },
        "train_$SSD_71$features": {
            "enum": [
                "raw",
                "white_delta",
                "cosine_delta",
                "pnorm_delta",
                "white",
                "cosine",
                "pnorm"
            ],
            "description": "preprocessing options. Normalize by stdev (white) or L2 (cosine) or None. Use raw or 'delta' from pretrained reference model"
        },
        "train_$SSD_71$normalize_for_feature_selection": {
            "type": "boolean",
            "description": "whether or not to apply normalization before feature selection"
        },
        "train_$SSD_71$sort_tensors": {
            "type": "boolean",
            "description": "whether or not to sort tensors"
        },
        "train_$FasterRCNN_83$nfeats": {
            "type": "integer",
            "minimum": 1,
            "description": "how many features to select",
            "suggested_minimum": 50,
            "suggested_maximum": 5000
        },
        "train_$FasterRCNN_83$ntensors": {
            "type": "integer",
            "minimum": 0,
            "description": "how many tensors select features from",
            "suggested_minimum": 5,
            "suggested_maximum": 100
        },
        "train_$FasterRCNN_83$cls_type": {
            "enum": [
                "LogisticRegression"
            ],
            "description": "name of classifier class (only LogisticRegression is currently supported)"
        },
        "train_$FasterRCNN_83$param_batch_sz": {
            "type": "integer",
            "minimum": 1,
            "description": "how many torch 'parameters' to look at at a time (trade off memory and disk reading)",
            "suggested_minimum": 80,
            "suggested_maximum": 80
        },
        "train_$FasterRCNN_83$C": {
            "type": "number",
            "minimum": 1e-09,
            "description": "sklearn-style regularization term.  Higher C -> less regularization. Must be positive",
            "suggested_minimum": 0.01,
            "suggested_maximum": 200.0
        },
        "train_$FasterRCNN_83$feature_selection_criterion": {
            "enum": [
                "corr",
                "auc"
            ],
            "description": "criterion for greedy feature selection"
        },
        "train_$FasterRCNN_83$features": {
            "enum": [
                "raw",
                "white_delta",
                "cosine_delta",
                "pnorm_delta",
                "white",
                "cosine",
                "pnorm"
            ],
            "description": "preprocessing options. Normalize by stdev (white) or L2 (cosine) or None. Use raw or 'delta' from pretrained reference model"
        },
        "train_$FasterRCNN_83$normalize_for_feature_selection": {
            "type": "boolean",
            "description": "whether or not to apply normalization before feature selection"
        },
        "train_$FasterRCNN_83$sort_tensors": {
            "type": "boolean",
            "description": "whether or not to sort tensors"
        }
    }
}

=== peratonlabs/Iliad-GIFT-lindet/config/final/r10E_metaparameters.json
{
    "train_$SSD_71$nfeats": 1000,
    "train_$SSD_71$cls_type": "LogisticRegression",
    "train_$SSD_71$param_batch_sz": 80,
    "train_$SSD_71$C": 1.0,
    "train_$SSD_71$feature_selection_criterion": "auc",
    "train_$SSD_71$normalize_for_feature_selection": true,
    "train_$SSD_71$features": "pnorm",
    "train_$SSD_71$ntensors": 25,
    "train_$SSD_71$sort_tensors": true,
    "train_$FasterRCNN_83$nfeats": 1000,
    "train_$FasterRCNN_83$cls_type": "LogisticRegression",
    "train_$FasterRCNN_83$param_batch_sz": 80,
    "train_$FasterRCNN_83$C": 3.0,
    "train_$FasterRCNN_83$feature_selection_criterion": "auc",
    "train_$FasterRCNN_83$normalize_for_feature_selection": true,
    "train_$FasterRCNN_83$features": "pnorm",
    "train_$FasterRCNN_83$ntensors": 25,
    "train_$FasterRCNN_83$sort_tensors": true
}
