=== peratonlabs/Iliad-GIFT-lindet/config/r16_metaparameters_schema.json
{
    "$id": "https://www.peratonlabs.com/r9gift.schema.json",
    "title": "PL-GIFT Algorithm Meta-Parameters",
    "technique": "Cosine-linear weight analysis",
    "technique_description": "Computes delta cosine features and classifies with a linear model",
    "technique_changes": "xxxxx",
    "technique_type": [
        "Weight Analysis"
    ],
    "commit_id": "xxxxx",
    "repo_name": "https://github.com/plgift/coslin",
    "$schema": "https://json-schema.org/draft-07/schema",
    "description": "TrojAI schema for the GIFT team, cos-lin method",
    "type": "object",
    "required": [
        "train_$FCModel_16$nfeats",
        "train_$FCModel_16$ntensors",
        "train_$FCModel_16$cls_type",
        "train_$FCModel_16$param_batch_sz",
        "train_$FCModel_16$C",
        "train_$FCModel_16$feature_selection_criterion",
        "train_$FCModel_16$features",
        "train_$FCModel_16$normalize_for_feature_selection",
        "train_$FCModel_16$sort_tensors",
        "train_$CNNModel_14$nfeats",
        "train_$CNNModel_14$ntensors",
        "train_$CNNModel_14$cls_type",
        "train_$CNNModel_14$param_batch_sz",
        "train_$CNNModel_14$C",
        "train_$CNNModel_14$feature_selection_criterion",
        "train_$CNNModel_14$features",
        "train_$CNNModel_14$normalize_for_feature_selection",
        "train_$CNNModel_14$sort_tensors"
    ],
    "additionalProperties": false,
    "properties": {
        "train_$FCModel_16$nfeats": {
            "type": "integer",
            "minimum": 1,
            "description": "how many features to select",
            "suggested_minimum": 50,
            "suggested_maximum": 5000
        },
        "train_$FCModel_16$ntensors": {
            "type": "integer",
            "minimum": 0,
            "description": "how many tensors select features from",
            "suggested_minimum": 5,
            "suggested_maximum": 100
        },
        "train_$FCModel_16$cls_type": {
            "enum": [
                "LogisticRegression"
            ],
            "description": "name of classifier class (only LogisticRegression is currently supported)"
        },
        "train_$FCModel_16$param_batch_sz": {
            "type": "integer",
            "minimum": 1,
            "description": "how many torch 'parameters' to look at at a time (trade off memory and disk reading)",
            "suggested_minimum": 80,
            "suggested_maximum": 80
        },
        "train_$FCModel_16$C": {
            "type": "number",
            "minimum": 1e-09,
            "description": "sklearn-style regularization term.  Higher C -> less regularization. Must be positive",
            "suggested_minimum": 0.01,
            "suggested_maximum": 200.0
        },
        "train_$FCModel_16$feature_selection_criterion": {
            "enum": [
                "corr",
                "auc"
            ],
            "description": "criterion for greedy feature selection"
        },
        "train_$FCModel_16$features": {
            "enum": [
                "raw",
                "white_delta",
                "cosine_delta",
                "pnorm_delta",
                "white",
                "cosine",
                "pnorm"
            ],
            "description": "preprocessing options. Normalize by stdev (white) or L2 (cosine) or None. Use raw or 'delta' from pretrained reference model"
        },
        "train_$FCModel_16$normalize_for_feature_selection": {
            "type": "boolean",
            "description": "whether or not to apply normalization before feature selection"
        },
        "train_$FCModel_16$sort_tensors": {
            "type": "boolean",
            "description": "whether or not to sort tensors"
        },
        "train_$CNNModel_14$nfeats": {
            "type": "integer",
            "minimum": 1,
            "description": "how many features to select",
            "suggested_minimum": 50,
            "suggested_maximum": 5000
        },
        "train_$CNNModel_14$ntensors": {
            "type": "integer",
            "minimum": 0,
            "description": "how many tensors select features from",
            "suggested_minimum": 5,
            "suggested_maximum": 100
        },
        "train_$CNNModel_14$cls_type": {
            "enum": [
                "LogisticRegression"
            ],
            "description": "name of classifier class (only LogisticRegression is currently supported)"
        },
        "train_$CNNModel_14$param_batch_sz": {
            "type": "integer",
            "minimum": 1,
            "description": "how many torch 'parameters' to look at at a time (trade off memory and disk reading)",
            "suggested_minimum": 80,
            "suggested_maximum": 80
        },
        "train_$CNNModel_14$C": {
            "type": "number",
            "minimum": 1e-09,
            "description": "sklearn-style regularization term.  Higher C -> less regularization. Must be positive",
            "suggested_minimum": 0.01,
            "suggested_maximum": 200.0
        },
        "train_$CNNModel_14$feature_selection_criterion": {
            "enum": [
                "corr",
                "auc"
            ],
            "description": "criterion for greedy feature selection"
        },
        "train_$CNNModel_14$features": {
            "enum": [
                "raw",
                "white_delta",
                "cosine_delta",
                "pnorm_delta",
                "white",
                "cosine",
                "pnorm"
            ],
            "description": "preprocessing options. Normalize by stdev (white) or L2 (cosine) or None. Use raw or 'delta' from pretrained reference model"
        },
        "train_$CNNModel_14$normalize_for_feature_selection": {
            "type": "boolean",
            "description": "whether or not to apply normalization before feature selection"
        },
        "train_$CNNModel_14$sort_tensors": {
            "type": "boolean",
            "description": "whether or not to sort tensors"
        }
    }
}

=== peratonlabs/Iliad-GIFT-lindet/config/r16D_metaparameters.json
{
    "train_$FCModel_16$nfeats": 1000,
    "train_$FCModel_16$cls_type": "LogisticRegression",
    "train_$FCModel_16$param_batch_sz": 80,
    "train_$FCModel_16$C": 0.1,
    "train_$FCModel_16$feature_selection_criterion": "auc",
    "train_$FCModel_16$normalize_for_feature_selection": true,
    "train_$FCModel_16$features": "pnorm_delta",
    "train_$FCModel_16$ntensors": 25,
    "train_$FCModel_16$sort_tensors": true,
    "train_$CNNModel_14$nfeats": 1000,
    "train_$CNNModel_14$cls_type": "LogisticRegression",
    "train_$CNNModel_14$param_batch_sz": 80,
    "train_$CNNModel_14$C": 0.1,
    "train_$CNNModel_14$feature_selection_criterion": "auc",
    "train_$CNNModel_14$normalize_for_feature_selection": true,
    "train_$CNNModel_14$features": "pnorm_delta",
    "train_$CNNModel_14$ntensors": 25,
    "train_$CNNModel_14$sort_tensors": true
}
