=== peratonlabs/Iliad-GIFT-lindet/config/r1_metaparameters_schema.json
{
    "$id": "https://www.peratonlabs.com/r9gift.schema.json",
    "title": "PL-GIFT Algorithm Meta-Parameters",
    "technique": "Cosine-linear weight analysis",
    "technique_description": "Computes delta cosine features and classifies with a linear model",
    "technique_changes": "xxxxx",
    "technique_type": [
        "Weight Analysis"
    ],
    "commit_id": "xxxxx",
    "repo_name": "https://github.com/plgift/coslin",
    "$schema": "https://json-schema.org/draft-07/schema",
    "description": "TrojAI schema for the GIFT team, cos-lin method",
    "type": "object",
    "required": [
        "train_$ResNet_161$nfeats",
        "train_$ResNet_161$ntensors",
        "train_$ResNet_161$cls_type",
        "train_$ResNet_161$param_batch_sz",
        "train_$ResNet_161$C",
        "train_$ResNet_161$feature_selection_criterion",
        "train_$ResNet_161$features",
        "train_$ResNet_161$normalize_for_feature_selection",
        "train_$ResNet_161$sort_tensors",
        "train_$DenseNet_364$nfeats",
        "train_$DenseNet_364$ntensors",
        "train_$DenseNet_364$cls_type",
        "train_$DenseNet_364$param_batch_sz",
        "train_$DenseNet_364$C",
        "train_$DenseNet_364$feature_selection_criterion",
        "train_$DenseNet_364$features",
        "train_$DenseNet_364$normalize_for_feature_selection",
        "train_$DenseNet_364$sort_tensors",
        "train_$Inception3_284$nfeats",
        "train_$Inception3_284$ntensors",
        "train_$Inception3_284$cls_type",
        "train_$Inception3_284$param_batch_sz",
        "train_$Inception3_284$C",
        "train_$Inception3_284$feature_selection_criterion",
        "train_$Inception3_284$features",
        "train_$Inception3_284$normalize_for_feature_selection",
        "train_$Inception3_284$sort_tensors"
    ],
    "additionalProperties": false,
    "properties": {
        "train_$ResNet_161$nfeats": {
            "type": "integer",
            "minimum": 1,
            "description": "how many features to select",
            "suggested_minimum": 50,
            "suggested_maximum": 5000
        },
        "train_$ResNet_161$ntensors": {
            "type": "integer",
            "minimum": 1,
            "description": "how many tensors select features from",
            "suggested_minimum": 5,
            "suggested_maximum": 100
        },
        "train_$ResNet_161$cls_type": {
            "enum": [
                "LogisticRegression"
            ],
            "description": "name of classifier class (only LogisticRegression is currently supported)"
        },
        "train_$ResNet_161$param_batch_sz": {
            "type": "integer",
            "minimum": 1,
            "description": "how many torch 'parameters' to look at at a time (trade off memory and disk reading)",
            "suggested_minimum": 80,
            "suggested_maximum": 80
        },
        "train_$ResNet_161$C": {
            "type": "number",
            "minimum": 1e-09,
            "description": "sklearn-style regularization term.  Higher C -> less regularization. Must be positive",
            "suggested_minimum": 0.01,
            "suggested_maximum": 200.0
        },
        "train_$ResNet_161$feature_selection_criterion": {
            "enum": [
                "corr",
                "auc"
            ],
            "description": "criterion for greedy feature selection"
        },
        "train_$ResNet_161$features": {
            "enum": [
                "raw",
                "white_delta",
                "cosine_delta",
                "pnorm_delta",
                "white",
                "cosine",
                "pnorm"
            ],
            "description": "preprocessing options. Normalize by stdev (white) or L2 (cosine) or None. Use raw or 'delta' from pretrained reference model"
        },
        "train_$ResNet_161$normalize_for_feature_selection": {
            "type": "boolean",
            "description": "whether or not to apply normalization before feature selection"
        },
        "train_$ResNet_161$sort_tensors": {
            "type": "boolean",
            "description": "whether or not to sort tensors"
        },
        "train_$DenseNet_364$nfeats": {
            "type": "integer",
            "minimum": 1,
            "description": "how many features to select",
            "suggested_minimum": 50,
            "suggested_maximum": 5000
        },
        "train_$DenseNet_364$ntensors": {
            "type": "integer",
            "minimum": 1,
            "description": "how many tensors select features from",
            "suggested_minimum": 5,
            "suggested_maximum": 100
        },
        "train_$DenseNet_364$cls_type": {
            "enum": [
                "LogisticRegression"
            ],
            "description": "name of classifier class (only LogisticRegression is currently supported)"
        },
        "train_$DenseNet_364$param_batch_sz": {
            "type": "integer",
            "minimum": 1,
            "description": "how many torch 'parameters' to look at at a time (trade off memory and disk reading)",
            "suggested_minimum": 80,
            "suggested_maximum": 80
        },
        "train_$DenseNet_364$C": {
            "type": "number",
            "minimum": 1e-09,
            "description": "sklearn-style regularization term.  Higher C -> less regularization. Must be positive",
            "suggested_minimum": 0.01,
            "suggested_maximum": 200.0
        },
        "train_$DenseNet_364$feature_selection_criterion": {
            "enum": [
                "corr",
                "auc"
            ],
            "description": "criterion for greedy feature selection"
        },
        "train_$DenseNet_364$features": {
            "enum": [
                "raw",
                "white_delta",
                "cosine_delta",
                "pnorm_delta",
                "white",
                "cosine",
                "pnorm"
            ],
            "description": "preprocessing options. Normalize by stdev (white) or L2 (cosine) or None. Use raw or 'delta' from pretrained reference model"
        },
        "train_$DenseNet_364$normalize_for_feature_selection": {
            "type": "boolean",
            "description": "whether or not to apply normalization before feature selection"
        },
        "train_$DenseNet_364$sort_tensors": {
            "type": "boolean",
            "description": "whether or not to sort tensors"
        },
        "train_$Inception3_284$nfeats": {
            "type": "integer",
            "minimum": 1,
            "description": "how many features to select",
            "suggested_minimum": 50,
            "suggested_maximum": 5000
        },
        "train_$Inception3_284$ntensors": {
            "type": "integer",
            "minimum": 1,
            "description": "how many tensors select features from",
            "suggested_minimum": 5,
            "suggested_maximum": 100
        },
        "train_$Inception3_284$cls_type": {
            "enum": [
                "LogisticRegression"
            ],
            "description": "name of classifier class (only LogisticRegression is currently supported)"
        },
        "train_$Inception3_284$param_batch_sz": {
            "type": "integer",
            "minimum": 1,
            "description": "how many torch 'parameters' to look at at a time (trade off memory and disk reading)",
            "suggested_minimum": 80,
            "suggested_maximum": 80
        },
        "train_$Inception3_284$C": {
            "type": "number",
            "minimum": 1e-09,
            "description": "sklearn-style regularization term.  Higher C -> less regularization. Must be positive",
            "suggested_minimum": 0.01,
            "suggested_maximum": 200.0
        },
        "train_$Inception3_284$feature_selection_criterion": {
            "enum": [
                "corr",
                "auc"
            ],
            "description": "criterion for greedy feature selection"
        },
        "train_$Inception3_284$features": {
            "enum": [
                "raw",
                "white_delta",
                "cosine_delta",
                "pnorm_delta",
                "white",
                "cosine",
                "pnorm"
            ],
            "description": "preprocessing options. Normalize by stdev (white) or L2 (cosine) or None. Use raw or 'delta' from pretrained reference model"
        },
        "train_$Inception3_284$normalize_for_feature_selection": {
            "type": "boolean",
            "description": "whether or not to apply normalization before feature selection"
        },
        "train_$Inception3_284$sort_tensors": {
            "type": "boolean",
            "description": "whether or not to sort tensors"
        }
    }
}

=== peratonlabs/Iliad-GIFT-lindet/config/r1G_metaparameters.json
{
    "train_$ResNet_161$nfeats": 1000,
    "train_$ResNet_161$cls_type": "LogisticRegression",
    "train_$ResNet_161$param_batch_sz": 80,
    "train_$ResNet_161$C": 0.3,
    "train_$ResNet_161$feature_selection_criterion": "auc",
    "train_$ResNet_161$normalize_for_feature_selection": true,
    "train_$ResNet_161$features": "pnorm",
    "train_$ResNet_161$ntensors": 0,
    "train_$ResNet_161$sort_tensors": true,
    "train_$DenseNet_364$nfeats": 1000,
    "train_$DenseNet_364$cls_type": "LogisticRegression",
    "train_$DenseNet_364$param_batch_sz": 80,
    "train_$DenseNet_364$C": 0.3,
    "train_$DenseNet_364$feature_selection_criterion": "auc",
    "train_$DenseNet_364$normalize_for_feature_selection": true,
    "train_$DenseNet_364$features": "pnorm",
    "train_$DenseNet_364$ntensors": 0,
    "train_$DenseNet_364$sort_tensors": true,
    "train_$Inception3_284$nfeats": 1000,
    "train_$Inception3_284$cls_type": "LogisticRegression",
    "train_$Inception3_284$param_batch_sz": 80,
    "train_$Inception3_284$C": 0.3,
    "train_$Inception3_284$feature_selection_criterion": "auc",
    "train_$Inception3_284$normalize_for_feature_selection": true,
    "train_$Inception3_284$features": "pnorm",
    "train_$Inception3_284$ntensors": 0,
    "train_$Inception3_284$sort_tensors": true
}
